version bump

diff --git a/tools/gh/wait-for-publish-to-finish b/tools/gh/wait-for-publish-to-finish
--- a/tools/gh/wait-for-publish-to-finish
+++ b/tools/gh/wait-for-publish-to-finish
@@ -3,23 +3,12 @@
 set -u
 set -e
 
+tag=$1
+
 echo "Waiting for GitHub workflow to start..."
 sleep 5
 
-s=""
-while [ "$s" !=	"completed" ]
-do
-	sleep 7
-  	s=$(curl -s -H "Accept: application/vnd.github.v3+json" -H "Authorization: token $GH_TOKEN" https://api.github.com/repos/mchmarny/vul/actions/runs | jq -r '[.workflow_runs[] | select(.name == "on_tag")] | .[0].status')
-	echo "Status: $s"
-done
+WID=$(gh run list -b $tag --json databaseId --jq '.[0].databaseId')
+[ -z "$WID" ] && echo "Workflow ID for $tag not found" && exit 1
 
-
-c=$(curl -s -H "Accept: application/vnd.github.v3+json" -H "Authorization: token $GH_TOKEN" https://api.github.com/repos/mchmarny/vul/actions/runs | jq -r '[.workflow_runs[] | select(.name == "on_tag")] | .[0].conclusion')
-
-if [ "$c" != "success" ]
-then
-	echo "Publish failed. See github logs for details:"
-	echo "https://github.com/mchmarny/vul/actions/workflows/on-tag.yaml"
-	exit 1
-fi
+gh run watch $WID
